#!/usr/bin/env bash

PHP_CS_FIXER="vendor/bin/php-cs-fixer"
HAS_PHP_CS_FIXER=false

if [ -x vendor/bin/php-cs-fixer ]; then
    HAS_PHP_CS_FIXER=true
fi

if $HAS_PHP_CS_FIXER; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        $PHP_CS_FIXER fix "$line";
        git add "$line";
    done
else
    echo ""
    echo "php-cs-fixer was not found, please run:"
    echo ""
    echo "  composer update --dev"
    echo ""
fi
